server:
  port: 8085
  context-path: /api
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

imgConfig:

  #Http Url
  localhost: http://pic.clvspk.com/

  #Server Storage
  basePath: home:photo:img